# Generated by Django 6.0.5 on 2026-05-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='es_Ok',
        ),
    ]
