# Generated by Django 5.2.14 on 2026-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_encuesta_estado_encuesta_fecha_cierre'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='encuestas_destinatarias', to='usuarios.usuario'),
        ),
    ]
